from django.urls import path
from . import views

urlpatterns = [
    path('',                                        views.home,                         name='home'),
    path('login/',                                  views.login_view,                   name='login'),
    path('logout/',                                 views.logout_view,                  name='logout'),
    path('register/',                               views.register_view,                name='register'),
    path('register/sent/',                          views.register_sent_view,           name='register_sent'),    
    path('verify-email/<str:token>/',               views.verify_email_view,            name='verify_email'),
    path('forgot-password/',                        views.forgot_password_view,         name='forgot_password'),
    path('forgot-password/sent/',                   views.forgot_password_sent_view,    name='forgot_password_sent'),
    path('reset-password/<str:token>/',             views.reset_password_view,          name='reset_password'),
    path('employee/dashboard/',                     views.employee_dashboard,           name='employee_dashboard'),
    path('employee/ngo/<int:ngo_id>/',              views.employee_ngo_detail,          name='employee_ngo_detail'),
    path('admin/dashboard/',                        views.admin_dashboard,              name='admin_dashboard'),
    path('admin/ngo/<int:ngo_id>/',                 views.admin_ngo_detail,             name='admin_ngo_detail'),
    path('admin/ngo/create/',                       views.admin_create_ngo,             name='admin_create_ngo'),
    path('admin/ngo/<int:ngo_id>/update/',          views.admin_update_ngo,             name='admin_update_ngo'),
    path('admin/ngo/<int:ngo_id>/delete/',          views.admin_delete_ngo,             name='admin_delete_ngo'),
    path('admin/ngo/<int:ngo_id>/toggle/',          views.admin_toggle_active,          name='admin_toggle_active'),
    path('admin/service-type/create/',              views.admin_create_service_type,    name='admin_create_service_type'),
    path('admin/service-type/<int:pk>/delete/',     views.admin_delete_service_type,    name='admin_delete_service_type'),
    path('admin/organizer/create/',                 views.admin_create_organizer,       name='admin_create_organizer'),
    path('admin/organizer/<int:pk>/delete/',        views.admin_delete_organizer,       name='admin_delete_organizer'),
    path('broadcast/',                              views.broadcast_view,               name='broadcast'),
    path('notification/log/',                       views.notification_log_view,        name='notification_log'),
    path('notification/settings/',                  views.notification_settings_view,   name='notification_settings'),
    path('registration/',                           views.registration_view,            name='registration'),
    path('registration/register/<int:ngo_id>/',     views.register_activity,            name='register_activity'),
    path('registration/cancel/',                    views.cancel_registration,          name='cancel_registration'),
    path('registration/switch/<int:ngo_id>/',       views.switch_registration,          name='switch_registration'),
    path('checkin/',                                views.checkin_view,                 name='checkin'),
    path('checkin/qr/<int:ngo_id>/',                views.generate_qr,                  name='generate_qr'),
    path('checkin/scan/',                           views.scan_view,                    name='scan_checkin'),
]